theme: jekyll-theme-minimal
title: Pierre Yves Schobbens' minimal Web page
description: A minimal page for when <a href="https://directory.unamur.be/staff/pyschobb?_LOCALE_=en">my University web page</a> is down. You can contact me at given-name.surname@unamur.be
logo: https://pds.unamur.be/presse/logos/unamur.png
